### ISSUE TITLE
challenge graphql response NotAllowed

### ISSUE THREAD

**Issue by renlong** [lens-protocol/api-examples#150]
request challenge graphql for https://api-v2.lens.dev/ response NotAllowed, what should i do?

```
{
	"operationName": "challenge",
	"query": "query challenge($request: ChallengeRequest!) {\n  challenge(request: $request) {\n    id\n    text\n  }\n}",
	"variables": {
		"request": {
			"signedBy": "0x790116d0685eB197B886DAcAD9C247f785987A4a",
			"for": "0x3bcb"
		}
	}
}
```

```
{
	"errors": [{
		"message": "NotAllowed",
		"locations": [{
			"line": 2,
			"column": 3
		}],
		"path": ["challenge"],
		"extensions": {
			"code": "UNAUTHENTICATED",
			"exception": {
				"stacktrace": ["AuthenticationError: NotAllowed", "    at validateCanUseProfile (/usr/src/app/packages/api-lens/lib/profile/operations/can-use-profile.js:22:15)", "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)", "    at async ChallengeRequest.validate (/usr/src/app/packages/api-lens/lib/authentication/resolvers/types/challenge-request.js:21:13)", "    at async AuthenticationQueriesResolver.challenge (/usr/src/app/packages/api-lens/lib/authentication/resolvers/queries/authentication.js:27:9)"]
			}
		}
	}],
	"data": null
}
```

**Comment by juangm** [comment]
Hi,

Based on the details you've provided, the issue typically arises when the wallet does not own the profile. I recommend attempting the process again using the appropriate links provided in our [API documentation](https://docs.lens.xyz/docs/api-links).

As I am unable to replicate the error on my end, I will be closing this ticket.
